EveronPackageGenerator:
  SchemaScopeConfigurator:
    property: [
      {name: name}
      {name: packageName}
      {name: namespace}
      {name: namespaceRoot}
      {name: vendor}
      {name: vendorName}
      {name: system}
      {name: systemName}
      {name: outputPath}
      {name: composerDescription}
      {name: composerType}
      {name: composerLicense}
    ]}}
